### ISSUE TITLE
UDP proxy has no effect on ENV:Windivert

### ISSUE THREAD

**Issue by lanslot-choby** [imgk/shadow#11]
The udp proxy has no effect, you can use [this tool](https://gist.github.com/lanslot-choby/02058118f6a78ed5b5134df406f3e0fd) to test it. When the shadow-windivert mode has taken effect, the udp request of the program will not be intercepted.

**Comment by imgk** [comment]
Can you show me your config file?

I'm not sure about your intention exactly. Though I understand the test program sends non-standard DNS requests to servers, like AdGuard DNS and some others, do you need these packets to be intercepted or not?

After adding these IPs of the servers to the config file, logs appeared.
![result](https://user-images.githubusercontent.com/14073640/90998420-a91a2580-e5f6-11ea-9e9e-300cede3b635.jpg)

**Comment by lanslot-choby** [comment]
```
{
	"Server": [
		"socks://127.0.0.1:8388"   // here is ss-local runed with udprelay...
	],
	
	"NameServer": "udp://8.8.8.8",
	
	"FilterString": "outbound and (ip ? ip.DstAddr != 8.8.8.8 and ip.DstAddr != 127.0.0.1 : true)",

    "AppRules": {
        "Proxy":[
            "xx.exe",
            "dig.exe",
            "curl.exe",
            "chrome.exe",
            "nslookup.exe"
        ]
    }
}
```

I am runing in the ss-local-Mode, tcp is ok,but udp not work.
When udp requested, the verbose log show nothing, udp packet used the old network environment.

**Comment by lanslot-choby** [comment]
You can test with my [ss-local](https://mega.nz/file/XvQ1VIqZ#30DttNIMFoYErbI1Sx-L2NNxnOkyh5q3rfGCcsgtlb4),I used go-tun2socks with it,and works well.

**Comment by imgk** [comment]
Commit 3c7a0fafa6a3176fe00e13943d853fea5999e729 may have fixed this issue.

**Comment by lanslot-choby** [comment]
Great!
Thank you very much,I have test your new commit,and it Fixed.
But could you check like my ss-local mode,configurate file like before I posted.My dns seems doesn't works very well..

**Comment by lanslot-choby** [comment]
Dear imgk,
I means, `"NameServer": "udp://8.8.8.8",` in my ss-local with udprelay mode, doesn't work.
DNS results are incorrect, DNS results ware modified by GFW

**Comment by imgk** [comment]
The dns queries captured by shadow will not be sent through proxy by default as these queries do not contain EDNS section which indicates the IP address of the client. The clean dns result may slow down the speed when browsing some websites. If you want to get clean dns result, please add `8.8.8.8/32` to `IPCIDRRules->Proxy` section, and change the `FilterString` to `outbound and not loopback and (ip ? ip.DstAddr != REMOTE-SERVER-IP : true)`. A more selective and precise filter string may improve performance.

**Comment by lanslot-choby** [comment]
Ok,not a very good solution,I think you can do the part of dns resolv better.
Thank you very much!
