### ISSUE TITLE
Support multiple servers to processes with the same name?

### ISSUE THREAD

**Issue by gnh1201** [imgk/shadow#12]
I'm thinking about how to establish individual sockets connections to processes with the same name. For example,

  * hello.exe (PID: 1) -> Socks A
  * hello.exe (PID: 10) -> Socks B
  * hello.exe (PID: 100) -> Socks C
  * bye.exe (PID: 2) -> Socks D
  * bye.exe (PID: 20) -> Socks E

How can I approach this problem?

**Comment by imgk** [comment]
Can you give more details about your intention. Currently shadow does not support multi servers. This feature can be added later.

Also you can not redirect connections to certain server by PID or process name as shadow doesn't support this type rule.

**Comment by imgk** [comment]
Yan can try [clash](https://github.com/Dreamacro/clash).
