### ISSUE TITLE
UDP(53) error...

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#17]
![image](https://user-images.githubusercontent.com/46304767/99867778-f90d8600-2bff-11eb-9300-2043024c5f27.png)

**Comment by imgk** [comment]
Could you share more information?

Use `wintun` or `WinDivert`?
What's your config file?

I can not reproduce this error.

**Comment by BeOB** [comment]
It is WinDivert.

**Comment by imgk** [comment]
Can you try this version?
Can you provide some information about your running environment?

[shadow.zip](https://github.com/imgk/shadow/files/5577153/shadow.zip)

Though I can not reproduce this error, I guess this error happens when the network card does not support checksum offload.

**Comment by BeOB** [comment]
Same error occurred....

![image](https://user-images.githubusercontent.com/46304767/99869956-8063f500-2c12-11eb-9e25-e93d318d9405.png)

**Comment by BeOB** [comment]
My lancard is suppert a udp checksum offload.

![image](https://user-images.githubusercontent.com/46304767/99870097-a8078d00-2c13-11eb-8c67-7f02308eb29c.png)

**Comment by imgk** [comment]
Try this version. If not, add `-tags="shadow_divert shadow_cgo"` to use previous LWIP instead of gvisor net stack. The previous one should work.

[shadow.zip](https://github.com/imgk/shadow/files/5577264/shadow.zip)

**Comment by BeOB** [comment]
![image](https://user-images.githubusercontent.com/46304767/99873905-b27f5200-2c26-11eb-88ee-e665a1493ce5.png)

**Comment by imgk** [comment]
fixed with 5bd4706

**Comment by imgk** [comment]
5bd4706 fix nil pointer

How about the checksum error?

**Comment by BeOB** [comment]
It has improved a lot.
But it dies after a few seconds.

![image](https://user-images.githubusercontent.com/46304767/99876406-d304d780-2c39-11eb-8906-646096c9df7e.png)

**Comment by BeOB** [comment]
End version is very nice.
You are the best.
Thanks..
