### ISSUE TITLE
How do you control the pure IP address?

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#2]
How do you control the pure IPv4 address at config.json ?

How do I reload config.json?

Thanks...

**Comment by imgk** [comment]
Currently, connections which are established with IPv4 adreesses that are not retrieving from a domain server will be just ignored. Shadowsocks-windivert can not handle this situation for now.

Restarting shadowsocks-windivert is the only way to reload config file. Live-reload will be added within the next release.
