### ISSUE TITLE
issue about shadow-wintun configuration

### ISSUE THREAD

**Issue by malikshi** [imgk/shadow#20]
`go build -v -ldflags="-s -w" -trimpath -tags="trojan" github.com/imgk/shadow
pkg\embed\embed.go:3:8: package embed is not in GOROOT (c:\go\src\embed)`
i didn't found embed

**Comment by malikshi** [comment]
updated go version fix embed errors, but other error come up
>panic: Error loading wintun.dll DLL: Unable to load library: The specified module could not be found.
goroutine 1 [running]:
golang.zx2c4.com/wireguard/tun/wintun.(*lazyProc).Addr(...)
        golang.zx2c4.com/wireguard@v0.0.20200321-0.20201111175144-60b3766b89b9/tun/wintun/dll_windows.go:56
golang.zx2c4.com/wireguard/tun/wintun.(*Pool).OpenAdapter(0xc000246000, 0xc000210ea0, 0x4, 0xd22f00, 0xc0002782a0, 0xc000211250)
        golang.zx2c4.com/wireguard@v0.0.20200321-0.20201111175144-60b3766b89b9/tun/wintun/wintun_windows.go:89 +0x22d
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID(0xc000210ea0, 0x4, 0xc000211250, 0x7fc, 0x52eeff, 0x10, 0xb9d780, 0xc00020c300)
        golang.zx2c4.com/wireguard@v0.0.20200321-0.20201111175144-60b3766b89b9/tun/tun_windows.go:73 +0x65
github.com/imgk/shadow/pkg/tun.CreateTUN(0xc000210ea0, 0x4, 0x7fc, 0xd22cc0, 0xc000204b00, 0xc000204af0)
        github.com/imgk/shadow/pkg/tun/tun_windows.go:63 +0x7c
github.com/imgk/shadow/pkg/tun.NewDeviceWithMTU(...)
        github.com/imgk/shadow/pkg/tun/tun.go:28
github.com/imgk/shadow/app.(*App).RunWithDevice(0xc00020c280, 0x0, 0x0, 0x0)
        github.com/imgk/shadow/app/tun.go:61 +0xd4b
github.com/imgk/shadow/app.(*App).Run(...)
        github.com/imgk/shadow/app/tun.go:113
main.main()
        github.com/imgk/shadow/main.go:61 +0x31f

**Comment by imgk** [comment]
You need to download WinTun manually.

https://www.wintun.net

**Comment by malikshi** [comment]
> You need to download WinTun manually.
> 
> https://www.wintun.net
for trojan issue how to modify this one
>"verify": true,
>"verify_hostname": true,
i want make it to false

**Comment by malikshi** [comment]
can you show me the configuration for Bypass LAN,
log
>Infor: 2021/02/25 07:23:17 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:17 handle udp error: invalid address type
Infor: 2021/02/25 07:23:18 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:18 handle udp error: invalid address type
Infor: 2021/02/25 07:23:19 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:19 handle udp error: invalid address type
Infor: 2021/02/25 07:23:20 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:20 handle udp error: invalid address type
Infor: 2021/02/25 07:23:21 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:22 handle udp error: invalid address type
Infor: 2021/02/25 07:23:22 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:23 handle udp error: invalid address type
Infor: 2021/02/25 07:23:23 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:24 handle udp error: invalid address type
Infor: 2021/02/25 07:23:24 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:24 handle udp error: invalid address type
Infor: 2021/02/25 07:23:25 hijack 192.168.0.11:64591 <-UDP-> 192.168.0.1:53
Infor: 2021/02/25 07:23:25 queryd 192.168.0.11:64591 ask for v10.events.data.microsoft.com.
Infor: 2021/02/25 07:23:25 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
Error: 2021/02/25 07:23:26 handle udp error: invalid address type
Infor: 2021/02/25 07:23:26 ignore packets to 239.255.255.250:1900

the current setting
>{
    "server": {
        "protocol": "trojan",
        "url": "trojan://pass@a.b.c.d:443#sni"
    },
    "name_server": "https://1.1.1.1:443/dns-query",
    "tun_name": "Tunnel",
    "tun_addr": ["192.168.0.11/24"]
}

**Comment by imgk** [comment]
> 
> 
> > You need to download WinTun manually.
> > https://www.wintun.net
> > for trojan issue how to modify this one
> > "verify": true,
> > "verify_hostname": true,
> > i want make it to false

Please refer to trojan-gfw or trojan-go. I'm not sure.

**Comment by imgk** [comment]
> 
> 
> can you show me the configuration for Bypass LAN,
> log
> 
> > Infor: 2021/02/25 07:23:17 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:17 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:18 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:18 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:19 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:19 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:20 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:20 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:21 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:22 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:22 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:23 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:23 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:24 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:24 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:24 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:25 hijack 192.168.0.11:64591 <-UDP-> 192.168.0.1:53
> > Infor: 2021/02/25 07:23:25 queryd 192.168.0.11:64591 ask for v10.events.data.microsoft.com.
> > Infor: 2021/02/25 07:23:25 proxyd 192.168.0.11:54915 <-UDP-> 192.168.0.255:54915
> > Error: 2021/02/25 07:23:26 handle udp error: invalid address type
> > Infor: 2021/02/25 07:23:26 ignore packets to 239.255.255.250:1900
> 
> the current setting
> 
> > {
> > "server": {
> > "protocol": "trojan",
> > "url": "trojan://pass@a.b.c.d:443#sni"
> > },
> > "name_server": "https://1.1.1.1:443/dns-query",
> > "tun_name": "Tunnel",
> > "tun_addr": ["192.168.0.11/24"]
> > }

As you have set `tun_addr` to `192.168.0.11/24`, all packets to these targets will be sent to shadow. You can change this address to another address.

**Comment by malikshi** [comment]
it's seem wrong?
>Infor: 2021/02/25 08:27:59 proxyd 198.168.0.11:54915 <-UDP-> 198.168.0.255:54915
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Infor: 2021/02/25 08:28:00 queryd 198.168.0.11:52525 ask for s.w.org.
Infor: 2021/02/25 08:28:00 proxyd 198.168.0.11:31240 <-TCP-> 1.1.1.1:443
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Infor: 2021/02/25 08:28:00 queryd 198.168.0.11:58706 ask for script.crazyegg.com.
Infor: 2021/02/25 08:28:00 proxyd 198.168.0.11:31242 <-TCP-> 1.1.1.1:443
Infor: 2021/02/25 08:28:00 queryd 198.168.0.11:64859 ask for ds6.whatismyipaddress.com.
Infor: 2021/02/25 08:28:00 proxyd 198.168.0.11:31244 <-TCP-> 1.1.1.1:443
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
Infor: 2021/02/25 08:28:00 queryd 198.168.0.11:61041 ask for a.pub.network.
Infor: 2021/02/25 08:28:00 proxyd 198.168.0.11:31246 <-TCP-> 1.1.1.1:443

my ipadress still original not even change to IP from server trojan

**Comment by imgk** [comment]
Can you post all your config here? It seems that your DNS server `https://1.1.1.1:443/dns-query` does not work properly.

**Comment by malikshi** [comment]
>{
    "server": {
        "protocol": "trojan",
        "url": "trojan://password@a.b.c.d:443#SNI"
    },
    "name_server": "https://1.1.1.1:443/dns-query",
    "tun_name": "Tunnel",
    "tun_addr": ["10.10.0.11/24"],
	"ip_cidr_rules": {
        "proxy": [
            "198.168.0.0/16",
            "1.1.1.1/32"
>        ]
>    }
>}

I am using Adguard windows and already deactivated it but still error DNS like the log above. just in case I tried using `tls://1.1.1.1:853` but seems to get an error too

**Comment by imgk** [comment]
This is the configuration I used. I can not reproduce the error showed above. According to the log showed above, the DNS server did not respond properly.

Shadow is mainly based on fake IP (`198.18.X.Y`) mode. To send data to the proxy server, you have to add IPs in the `ip_cidr_rules.proxy` or domains in the `domain_rules.proxy`

In your configuration, packets targeting `1.1.1.1/32` or `198.168.0.0/16` will be sent to the proxy server. As you have set the DNS server to `https://1.1.1.1/dns-query`, all your DNS queries will be sent through the proxy server. 

```
Error: 2021/02/25 08:28:00 resolve dns error: Post "https://1.1.1.1:443/dns-query": http: server gave HTTP response to HTTPS client
```

You should check DNS queries on the proxy server first. As the log indicated, `1.1.1.1` sends an HTTP response to an HTTPS request. I think there might be some reasons that your proxy server can not connect `1.1.1.1` properly. Also, you can try other DNS servers, like Google's `8.8.8.8`.

As the fake IP mode needs to hijack all your DNS queries and you used Adguard before, you may have to recheck your DNS settings.

```json
{
    "server": {
        "protocol": "trojan",
        "url": "trojan://pass@a.b.c.d:443#SNI"
    },
    "name_server": "https://1.1.1.1:443/dns-query",
    "tun_name": "Tunnel",
    "tun_addr": ["10.10.0.11/24"],
    "ip_cidr_rules": {
        "proxy": [
            "198.18.0.0/16",
            "1.1.1.1/32"
        ]
    },
    "domain_rules": {
        "proxy": [
            "**.google",
            "**.google.*"
        ],
        "direct": [
            "**.*"
        ],
        "blocked": [
        ]
    }
}
```

**Comment by malikshi** [comment]
yes, indeed my VPS somehow can't connect properly with Cloudflare DNS. I did try using Google DNS, `https://dns.google:443/dns-query` is it wrong? should I put `https://8.8.8.8:443/dns-query`. I will try out all the options later.

**Comment by imgk** [comment]
I prefer `https://8.8.8.8:443/dns-query`.

**Comment by malikshi** [comment]
> I prefer `https://8.8.8.8:443/dns-query`.

![Screenshot_1105](https://user-images.githubusercontent.com/9080737/109138765-4d8b4900-778d-11eb-83ff-149835f0bb90.jpg)
I tried but with no success, it's the same errors. I'm changing different servers that support DNS Cloudflare with your example config.

**Comment by imgk** [comment]
Which trojan server are you using? I can not reproduce this error so I do not know the exact reason. Have you tested your server with trojan-go or trojan-gfw as client? I guess the password is wrong?

**Comment by malikshi** [comment]
> Which trojan server are you using? I can not reproduce this error so I do not know the exact reason. Have you tested your server with trojan-go or trojan-gfw as client? I guess the password is wrong?

it's work fine with trojan-gfw client and igniter(android client) and trough openwrt too.

**Comment by imgk** [comment]
This is the trojan-go server config I'm using.

```json
{
  "run_type": "server",
  "local_addr": "0.0.0.0",
  "local_port": 443,
  "remote_addr": "127.0.0.1",
  "remote_port": 80,
  "password": [
    "pass1234"
  ],
  "ssl": {
    "cert": "/example.crt",
    "key": "/example.key",
    "sni": "example.cc"
  },
  "mux": {
    "enabled": true,
    "concurrency": 8,
    "idle_timeout": 60
  },
  "router": {
    "enabled": false,
    "block": [
      "geoip:private"
    ],
    "geoip": "/usr/share/trojan-go/geoip.dat",
    "geosite": "/usr/share/trojan-go/geosite.dat"
  }
}
```

**Comment by imgk** [comment]
Do you have special characters for your password?

**Comment by malikshi** [comment]
yes im using `:` and `-`

**Comment by imgk** [comment]
So your url will be trojan://sss:rrr@1.2.3.4:443#sni? Shadow can not parse url like that.  Try replacing : with %3A.

https://www.w3schools.com/tags/ref_urlencode.ASP
https://www.urlencoder.org/

**Comment by malikshi** [comment]
>> So your url will be trojan://sss:rrr@1.2.3.4:443#sni? Shadow can not parse url like that. Try replacing : with %3A.
>> 
>> https://www.w3schools.com/tags/ref_urlencode.ASP
>> https://www.urlencoder.org/

>Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:59784 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:63673 ask for sync.search.spotxchange.com.
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:49550 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:51813 ask for t.wayfair.com.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:50513 ask for sync.crwdcntrl.net.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:59784 ask for p.rfihub.com.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:49550 ask for t.mookie1.com.
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:51585 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:51585 ask for prebid.adnxs.com.
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:60085 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:61073 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:60085 ask for nep.advangelists.com.
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:54335 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:61073 ask for rbp.mxptint.net.
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:52461 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:54209 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:50421 <-UDP-> 10.10.0.1:53
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:50421 ask for secure.adnxs.com.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:54335 ask for match.prod.bidr.io.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:52461 ask for tr.blismedia.com.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:54209 ask for sync.srv.stackadapt.com.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:53689 ask for ad.turn.com.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:59784 ask for p.rfihub.com.
Infor: 2021/02/26 01:50:13 queryd 10.10.0.11:49550 ask for t.mookie1.com.
Infor: 2021/02/26 01:50:13 hijack 10.10.0.11:63666 <-UDP-> 10.10.0.1:53

Somehow it's work but no changes on my IP while browsing? Isn't for global setting right with only bypass LAN?

**Comment by imgk** [comment]
I have mentioned that shadow is mainly based on fake IP mode, so it is designed to proxy what you need and ignore others. To work as a global proxy and bypass LAN with WinTun, you need to modify the route table by yourself to force all packets to send through WinTun.

https://www.howtogeek.com/howto/windows/adding-a-tcpip-route-to-the-windows-routing-table/
