### ISSUE TITLE
关于shadow的原理问题

### ISSUE THREAD

**Issue by leiless** [imgk/shadow#21]
作者你好，由于我怕英文表意不准确，因此考虑直接用中文问你好了。

最近有空想学习一下shadow的源码，但是由于这网络技术栈方面经验欠缺，加上之前稍微看了下代码，不太明白的实现原理。

目前shadow用WinTun, WinDivert, gVisor几个不同的组件来分别实现透明代码，加上Fake IP mode，但是他们之间是怎么联动起来的不是太明白。

如果你有时间的话，可以大概跟我描绘一下整个blueprint和大概的一些细节吗？非常感谢 🤣

**Comment by imgk** [comment]
之前的源码比较混乱，毕竟一边写一边增加功能，现在再看应该就好多了。

细节你自己看代码，大致思路就是从 Tun/WinTun/WinDivert 读取 IP 数据包，写进 gVisor 网络栈，网络栈上注册 `HandlePacket` 函数用于处理 TCP 和 UDP，将 `gonet.Conn` 和 `gonet.PacketConn` 传给 `proto` 里实现的 `gonet.Handler` 处理。

Tun/WinTun 的数据包获取通过修改路由表实现。WinDivert 则通过写了一个 `PacketFilter` 按 IP、 进程名或 IP 地理位置信息将指定的数据包拦截并发送到网络栈。

Fake IP 通过拦截所有的 UDP 53 的数据，根据域名分配 fake IP 或直接发送 DNS 服务器。

大致就这样

**Comment by leiless** [comment]
> Fake IP 通过拦截所有的 UDP 53 的数据，根据域名分配 fake IP 或直接发送 DNS 服务器。

我简单理解一下，
意思是针对UDP 53的DNS请求，如果规则命中，那么就返回一个Fake IP的A/AAAA记录？
也即是说Fake IP只有这一种使用场景对吗？

**Comment by imgk** [comment]
在 `domain_rules.proxy` 中的域名返回 `198.18.X.Y` 开头的 A 记录，没有 AAAA 记录，还要加入 PTR 记录，用来将 fake IP 还原成实际的域名

**Comment by leiless** [comment]
感谢解答~

**Comment by briteming** [comment]
我在安装时，看到它用到了github.com/eycorsican/go-tun2socks的代码

**Comment by imgk** [comment]
> 我在安装时，看到它用到了github.com/eycorsican/go-tun2socks的代码

I have removed that.
