### ISSUE TITLE
Unable to load WinTun for Windows 7 unsign error

### ISSUE THREAD

**Issue by ghost** [imgk/shadow#29]
according official wintun [https://www.wintun.net/](url) info,dll has already signed.

> Wintun is distributed as a simple ZIP archive containing **signed DLLs for AMD64, X86, ARM64, and ARM32**, along with the wintun.h header file for applications. Note that the below signed DLLs are the only supported way of distributing Wintun. The prebuilt signed DLLs are released under a more permissive license than GPL 2.0, included in the ZIP archive.

But i got this:

![image](https://user-images.githubusercontent.com/17429958/112938345-06152580-915c-11eb-92f6-83278bd37b49.png)

**Comment by imgk** [comment]
Can you test WireGuard? If you get an error too, I think it is an issue with WinTun. I have no Windows 7 machine to test.

https://github.com/WireGuard/wireguard-go

I remember that Windows 7 does not support SHA256 algorithm natively, and you need to install additional support.

https://support.microsoft.com/en-us/topic/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus-64d1c82d-31ee-c273-3930-69a4cde8e64f

https://stackoverflow.com/questions/49901600/sha256-signed-drivers-not-working-in-win7-64-bit

https://nvidia.custhelp.com/app/answers/detail/a_id/5002/~/driver-installation-issues-on-windows-7

**Comment by ghost** [comment]
That's a SHA256 bug.
I fixed it!
Awesome
