### ISSUE TITLE
config.json文件的内容该怎么写？

### ISSUE THREAD

**Issue by luckypoem** [imgk/shadow#32]
能在此贴出一个示范的config.json文件的内容吗

**Comment by imgk** [comment]
You should read this carefully https://github.com/imgk/shadow/blob/main/doc/configuration.md. And you should provide your context.

**Comment by luckypoem** [comment]
hi.
我 仔细读了它。
cat config.json
显示：
{
"server": {
        "protocol": "socks5",
        "url": socks://127.0.0.1:2553
},

  "tun": {
        "tun_name": "utun8",
        "tun_addr": ["192.168.0.11/24"]
    },

"ip_cidr_rules": {
        "proxy": [
            "198.18.0.0/16",
            "8.8.8.8/32"
        ]
    }

}

然后，
shadow -c config.json
显示：
2021/04/19 10:30:12 invalid character 's' looking for beginning of value
panic: invalid character 's' looking for beginning of value

goroutine 1 [running]:
log.Panic(0xc00020bee8, 0x1, 0x1)
	/Users/brite/go1.16.3/go/src/log/log.go:354 +0xae
main.main()
	/Users/brite/shadow/main.go:61 +0x2e5

怎么回事？配置文件写错了吗

**Comment by imgk** [comment]
You can use vs code to check the format.

Please check server.url.

**Comment by luckypoem** [comment]
hi。

我是Mac系统，我没有visual studio程序。
server.url哪里写错了？能具体指出来或帮我改过来吗？
谢谢你！

**Comment by imgk** [comment]
VS Code is not Visual Studio. For macOS, you should run shadow with `sudo`. Shadow runs as fake IP mode, you should add domains in `domain_rules.proxy`.

```json
{
  "server": {
    "protocol": "socks5",
    "url": "socks://127.0.0.1:2553"
  },
  "name_server": "https://1.1.1.1:443/dns-query",
  "tun": {
    "tun_name": "utun",
    "tun_addr": [
      "192.168.0.11/24"
    ]
  },
  "ip_cidr_rules": {
    "proxy": [
      "198.18.0.0/16",
      "8.8.8.8/32"
    ]
  },
  "domain_rules": {
    "proxy": ["**.google.*"],
    "direct": ["**.*"],
    "blocked": []
  }
}
```

**Comment by luckypoem** [comment]
我 估计是我的shadow没有真正编译成功，shadow的可执行文件有问题。
你可否提供mac系统上的可执行文件下载地址呢？放在releases.
tks very very much

**Comment by imgk** [comment]
How to use shadow on macOS:

1. Set system DNS server to `8.8.8.8`
2. Prepare `config.json`. Add domains you want to proxy in `domain_rules.proxy`.
```json

{
  "server": {
    "protocol": "socks5",
    "url": "socks://127.0.0.1:2553"
  },
  "name_server": "https://223.5.5.5:443/dns-query",
  "tun": {
    "tun_name": "utun",
    "tun_addr": [
      "192.168.0.11/24"
    ]
  },
  "ip_cidr_rules": {
    "proxy": [
      "198.18.0.0/16",
      "8.8.8.8/32"
    ]
  },
  "domain_rules": {
    "proxy": ["**.google.*"],
    "direct": ["**.*"],
    "blocked": []
  }
}
```
3. Run `sudo go/bin/shadow -c config.json -v`.

If you got an error, please show me the message. So I can help you.

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:~ brite$ shadow -c shadow-config-2.json
2021/04/20 10:11:29 protocol error: not a supported scheme: socks5
panic: protocol error: not a supported scheme: socks5

goroutine 1 [running]:
log.Panic(0xc000213ee8, 0x1, 0x1)
	/Users/brite/go1.16.3/go/src/log/log.go:354 +0xae
main.main()
	/Users/brite/shadow/main.go:66 +0x35c
yudeMacBook-Air:~ brite$

匪夷所思啊，怎么提示“not a supported scheme: socks5”？

cat shadow-config-2.json
显示：
{
  "server": {
    "protocol": "socks5",
    "url": "socks://127.0.0.1:2553"
  },
  "name_server": "https://1.1.1.1:443/dns-query",
  "tun": {
    "tun_name": "utun",
    "tun_addr": [
      "192.168.0.11/24"
    ]
  },
  "ip_cidr_rules": {
    "proxy": [
      "198.18.0.0/16",
      "8.8.8.8/32"
    ]
  },
  "domain_rules": {
    "proxy": ["**.google.*"],
    "direct": ["**.*"],
    "blocked": []
  }
}

**Comment by imgk** [comment]
See https://github.com/imgk/shadow#how-to-build. You have to add the proxy name to build tags.

```
go get -v -ldflags="-s -w" -trimpath -tags="socks" github.com/imgk/shadow
```

**Comment by luckypoem** [comment]
hi

yudeMacBook-Air:gopath brite$ go get -u -v -ldflags="-s -w" -trimpath -tags="socks5" github.com/imgk/shadow

pkg/mod/gvisor.dev/gvisor@v0.0.0-20210420015027-82eecd2e93a4/pkg/tcpip/socketops.go:21:2: found packages sync (aliases.go) and seqatomic (generic_atomicptr_unsafe.go) in /Users/brite/go1.16.3/go/gopath/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210420015027-82eecd2e93a4/pkg/sync
pkg/mod/gvisor.dev/gvisor@v0.0.0-20210420015027-82eecd2e93a4/pkg/tcpip/adapters/gonet/gonet.go:30:2: found packages tcp (accept.go) and rcv (rcv_test.go) in /Users/brite/go1.16.3/go/gopath/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210420015027-82eecd2e93a4/pkg/tcpip/transport/tcp
yudeMacBook-Air:gopath brite$ which shadow
yudeMacBook-Air:gopath brite$

没有go get成功？怎么解决？

**Comment by imgk** [comment]
Do not add `-u`.

**Comment by luckypoem** [comment]
hi.

这次没加-u ，go get成功。

yudeMacBook-Air:~ brite$ cat shadow-config-2.json
{
"server": {
"protocol": "socks5",
"url": "socks://127.0.0.1:2553"
},

"name_server": "https://1.1.1.1:443/dns-query",

"tun": {
"tun_name": "utun8",
"tun_addr": [
"192.168.0.11/24"
]
},

"ip_cidr_rules": {
"proxy": [
"198.18.0.0/16",
"8.8.8.8/32"
]
},

"domain_rules": {
"proxy": [
".google.*"
"**.google.com",
            "**.google.*",
            "**.google.*.*",
            "**.youtube.com",
            "*.twitter.com",
            "www.facebook.com",
            "bing.com",
"*.blogspot.com"
],

"direct": [".*"],
"blocked": []
}

}
yudeMacBook-Air:~ brite$ shadow -c shadow-config-2.json
2021/04/20 13:47:43 invalid character '"' after array element
panic: invalid character '"' after array element

goroutine 1 [running]:
log.Panic(0xc000213ee8, 0x1, 0x1)
	log/log.go:354 +0xae
main.main()
	github.com/imgk/shadow@v0.0.0-20210414002156-65c4532054b4/main.go:61 +0x2e5
yudeMacBook-Air:~ brite$ shadow -c shadow-config-2.json -v
2021/04/20 13:49:53 invalid character '"' after array element
panic: invalid character '"' after array element

goroutine 1 [running]:
log.Panic(0xc000213ee8, 0x1, 0x1)
	log/log.go:354 +0xae
main.main()
	github.com/imgk/shadow@v0.0.0-20210414002156-65c4532054b4/main.go:61 +0x2e5
yudeMacBook-Air:~ brite$

提示说：invalid character '"' after array element。它指哪个无效的字符？哪个双引号？

**Comment by imgk** [comment]
Please do not waste our time. Use a tool to check your json format. Just google it.

**Comment by luckypoem** [comment]
sorry.原来是这行 ".google.*"  没加逗号。我在这https://www.bejson.com/验证的。
不过加了逗号后，

yudeMacBook-Air:~ brite$ shadow -c shadow-config-2.json
2021/04/20 15:25:42 protocol error: not a supported scheme: socks5
panic: protocol error: not a supported scheme: socks5

goroutine 1 [running]:
log.Panic(0xc00021bee8, 0x1, 0x1)
	log/log.go:354 +0xae
main.main()
	github.com/imgk/shadow@v0.0.0-20210414002156-65c4532054b4/main.go:66 +0x35c
yudeMacBook-Air:~ brite$

还是出现提示： not a supported scheme: socks5。真是活见鬼了。

**Comment by imgk** [comment]
Wrong tags. Use `socks`.

**Comment by luckypoem** [comment]
这次成功。不容易。如果不是楼主热心解答疑问，我可能已放弃此项目。
另外，建议楼主把项目里，所有提到socks5之处全部改为socks，免得造成混乱和错误。

**Comment by luckypoem** [comment]
我修改了一下配置文件：
yudeMacBook-Air:~ brite$ cat shadow-config.json
{
"server": {
        "protocol": "socks",
        "url": "socks://127.0.0.1:2553"
},

"name_server": "https://8.8.8.8:443/dns-query",

  "tun": {
        "tun_name": "utun8",
        "tun_addr": ["192.168.0.11/24"]
    },

"ip_cidr_rules": {
        "proxy": [
"198.18.0.0/16",
"8.8.8.8/32"
]
    },

"domain_rules": 
{
    "proxy": [
"**.google.com",
"**.youtube.com",
"**.twitter.com",
"**.facebook.com",
"**.blogspot.com"
],
"direct": [],
"blocked": []
}

}
yudeMacBook-Air:~ brite$
yudeMacBook-Air:~ brite$ sudo shadow -c shadow-config.json
Password:
2021/04/21 15:07:16 add route entry error: write to socket error: file exists
panic: add route entry error: write to socket error: file exists

goroutine 1 [running]:
log.Panic(0xc000125ee8, 0x1, 0x1)
	log/log.go:354 +0xae
main.main()
	github.com/imgk/shadow@v0.0.0-20210414002156-65c4532054b4/main.go:66 +0x35c
yudeMacBook-Air:~ brite$

how to fix it?

**Comment by imgk** [comment]
Reboot

**Comment by luckypoem** [comment]
不过翻墙速度好慢。有什么办法尽量改善速度吗？
