### ISSUE TITLE
Support geosite.dat and faster DomainMatcher implementation

### ISSUE THREAD

**Issue by LazyZhu** [imgk/shadow#33]
[geosite.dat](https://github.com/v2fly/domain-list-community)
[v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)

https://github.com/XTLS/Xray-core/pull/348

**Comment by imgk** [comment]
I have read the links you showed. I didn't find instructions about how to use `geosite.dat` with golang. Did I miss something?

Currently, I do not have spare time for this project. And everything works well. PR is welcome and if you need any help. Please let me know.

**Comment by LazyZhu** [comment]
> V2Ray 路由规则文件加强版，可代替 V2Ray 官方 geoip.dat 和 geosite.dat，兼容 Shadowsocks-windows、Xray-core、Trojan-Go 和 leaf。

V2Ray, Xray-core, Trojan-Go are golang based...

**Comment by imgk** [comment]
I understand what you are trying to express. However, I have no time to do these things.

I put gfwlist in `domain_rules.proxy` and the query time is only 2 ms.

PR is welcome.

```
C:\Users\imgk>dig google.com

; <<>> DiG 9.17.9 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4612
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 3a41636bbc931044 (echoed)
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             1       IN      A       198.18.37.85

;; Query time: 2 msec
;; SERVER: 211.138.180.2#53(211.138.180.2) (UDP)
;; WHEN: Tue Apr 20 10:02:28 ;; MSG SIZE  rcvd: 77
```

**Comment by imgk** [comment]
@LazyZhu Can you try the dev branch?

```jsonc
{
    "domain_rules": {
        "geo_site": {
          "file": "geosite.dat",
          "proxy": [],
          "bypass": ["CN"],
          "final": "proxy",
        },
        "proxy": [],
        "direct": [],
        "blocked": []
    }
}
```
