### ISSUE TITLE
error in openwrt while routing

### ISSUE THREAD

**Issue by malikshi** [imgk/shadow#34]
hello, I just build with the latest repo and works in windows but in Linux says
>2021/05/22 17:34:08 add route entry error: ioctl: SIOCADDRT: invalid argument
panic: add route entry error: ioctl: SIOCADDRT: invalid argument

I am using RPI4b with OpenWRT 19.07 snapshot

**Comment by imgk** [comment]
The only thing I can tell without your config file is that there must be something wrong with your config file. Delete entries in `ip_cidr_rules.proxy` and add them one by one. And you will know which one is invalid.

This is the config file I'm using.

```
{
  "server": {
    "url": "trojan://test1234@1.2.3.4:443/?transport=http2#test.cc",
    "protocol": "trojan"
  },
  "name_server": ["https://223.5.5.5:443/dns-query"],
  "tun": {
    "tun_name": "shadow",
    "tun_addr": [
      "192.168.0.11/24"
    ]
  },
  "ip_cidr_rules": {
    "proxy": [
      "198.18.0.0/16",
      "8.8.8.8/32"
    ]
  },
  "domain_rules": {
    "proxy": [
      "**.*"
    ],
    "direct": [
    ],
    "blocked": []
  }
}
```

**Comment by malikshi** [comment]
@imgk i am using your config reference in from my lastime issues
>{
   "server":{
      "protocol": "trojan",
      "url":"trojan://pass@a.b.c.d:443#domain"
   },
   "name_server":["https://1.1.1.1:443/dns-query"],
   "tun_name":"VPN0",
   "tun_addr":[
      "192.168.0.11/24"
   ],
   "ip_cidr_rules":{
      "proxy":[
         "198.18.0.0/16",
         "1.1.1.1/32"
      ]
   },
   "domain_rules":{
      "proxy":[
         "**.*"
      ],
      "direct":[],
      "blocked":[]
   }
}

and updated `"name_server":"https://1.1.1.1:443/dns-query"` to this `"name_server":["https://1.1.1.1:443/dns-query"]` it's work in windows but in openwrt doesn't work

**Comment by imgk** [comment]
Shadow provides a DNS-based solution. If shadow is running on OpenWRT, you can use `dig` or `nslookup` to check your DNS setting. If shadow handles DNS queries correctly, you will get an IP with a prefix of `198.18` for domains in `domain_rules.proxy`. As you have added `1.1.1.1/32` in `ip_cidr_rules.proxy`, you can set your system DNS server to `1.1.1.1`. Or you can set `1.1.1.1` as dnsmasq's upstream.

Don't forget to set up the firewall for OpenWRT.

```
export TunName=VPN0
iptables -I FORWARD -o $TunName -j ACCEPT
iptables -t nat -I POSTROUTING -o $TunName -j MASQUERADE
```

**Comment by malikshi** [comment]
> hello, I just build with the latest repo and works in windows but in Linux says
> 
> > 2021/05/22 17:34:08 add route entry error: ioctl: SIOCADDRT: invalid argument
> > panic: add route entry error: ioctl: SIOCADDRT: invalid argument
> 
> I am using RPI4b with OpenWRT 19.07 snapshot

This the errors. Is it related to route the interface type wireguard?

**Comment by imgk** [comment]
This error happens when adding an entry to route table. Delete all items in `ip_cidr_rules.proxy` and add route manually. I use OpenWRT 19.07 too, and I can't reproduce this error. So I don't know what causes this error. Please check `ip_cidr_rules.proxy`. There must be something wrong with it.
