### ISSUE TITLE
关于shadow的托管流量的原理问题

### ISSUE THREAD

**Issue by xiran2018** [imgk/shadow#38]
本文小白一枚，我对shadow如何托管系统的流量有点疑问
看到了https://github.com/imgk/shadow/issues/21，大概了解了原理，我还有一个问题想问一下：

【原理阐述】
https://github.com/imgk/shadow/issues/21#issuecomment-786478537
您在上面说道： 从 Tun/WinTun读取 IP 数据包，Tun/WinTun 的数据包获取通过修改路由表实现。WinDivert 则通过写了一个 PacketFilter 按 IP、 进程名或 IP 地理位置信息将指定的数据包拦截并发送到网络栈。

【问题】
WinDivert是windows下用的。linux和mac是如何实现按 IP、 进程名或 IP 地理位置信息将指定的数据包拦截并发送到gVisor网络栈上的呢？

**Comment by imgk** [comment]
然而在macOS及Linux上并不支持进程和地理位置规则

**Comment by xiran2018** [comment]
哦，也就是说在windows下，数据包的流向是 wintun--->WinDivert---->gVisor
在mac和linux下，数据包的流向是 tun---->gVisor
不知道我理解的是否正确

**Comment by imgk** [comment]
WinTun和WinDivert用一个就好了，并不是串在一起

**Comment by xiran2018** [comment]
哦，是这样呀，我理解错了，多谢多谢
