### ISSUE TITLE
Shadow not proxing

### ISSUE THREAD

**Issue by xp0s3d0** [imgk/shadow#39]
Hello, Im trying to use this software but its not working as expected.
I  built it using: `go1.17 windows/amd64`
##update: tried with go1.16 and seems nothing changed##
With the following cmd:
`go get -v -ldflags="-s -w" -trimpath -tags="divert http" github.com/imgk/shadow`

I tried to access both amazon.com and facebook.com that I put inside "blocked" and I can access them normally.
Also by trying to access any ip finder website it just output my my normal ip not the one of the proxy

This is the config file for testing that Ive used:
```
{
  "server": {
    "protocol": "http",
    "url": "http://x.x.x.x:yyyy"
  },
  "name_server": [ "https://1.1.1.1:443/dns-query" ],
  "windivert_filter_string": "outbound and tcp and tcp.DstPort == 443",
  "domain_rules": {
    "proxy": [
     "**.*"
    ],
    "direct": [
      "**.youtube.com",
      "*.twitter.com",
       "*.myip.com"

    ],
    "blocked": [
	"**.amazon.*",
	"www.facebook.com"
    ]
  }
}
```

**Comment by imgk** [comment]
Shadow is based on DNS, so you have to divert DNS queries to shadow.
