### ISSUE TITLE
Some execute fine, others don't.

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#4]
Some execute fine, others don't.
(It's a different computer, but I'm using the same Windows 10 64bit)
![image](https://user-images.githubusercontent.com/46304767/79464207-bc0f5e80-8034-11ea-92e1-bcbcfc5b22c6.png)

----
config.json

{
    "Server": "ss://aes-256-gcm:pass@127.0.0.1:8388",
    "NameServer": "127.0.0.1:5300=https://cloudflare-dns.com/dns-query",
    "IPCIDR": ["44.44.0.0/16"],
    "Programs": ["msedge.exe"],
    "Proxy": [],
    "Direct": [],
    "Blocked": []
}

**Comment by imgk** [comment]
Do you have a golang build environment? If you have, you can build a cmd version and run with -v option. Logs showing in the cmd window are essential to locate the problem.

**Comment by BeOB** [comment]
I did not compile and downloaded and used the binary file.
This option(-v) doesn't work.

**Comment by imgk** [comment]
It works. But the logs won’t show in the cmd window. That’s the reason why you have to build a cmd version. It’s a feature of Windows.

**Comment by BeOB** [comment]
![image](https://user-images.githubusercontent.com/46304767/79517945-a3ca2e80-808a-11ea-81a3-6a891ba13f01.png)

**Comment by BeOB** [comment]
Can you tell me your compilation options?

**Comment by imgk** [comment]
To build this program, you need golang and mingw. 

1. Install golang and mingw. Add dirs which contain gcc.exe and go.exe to PATH environment variable.

2. Run windres.exe to build icon resource.

windres.exe -o main.syso main.rc

3. Run go build.

**Comment by BeOB** [comment]
### 
![image](https://user-images.githubusercontent.com/46304767/79520608-37532d80-8092-11ea-8daf-970513e9667f.png)
What is the problem?

**Comment by imgk** [comment]
The program panics because it can not find `WinDivert64.sys/WinDivert32.sys` in the working directory. Before running the cmd version, you have to change directory to the one which contains these files, like `cd C:/path/to/shadowsocks-windivert.exe`. If this error recurs, I have no idea about this problem because this is a issue about [Divert](https://github.com/basil00/Divert).

**Comment by BeOB** [comment]
I find it.

![image](https://user-images.githubusercontent.com/46304767/79525556-1a245c00-809e-11ea-9520-5e023b792bb9.png)
