### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by yansong1221** [imgk/shadow#40]
这个dns怎么用的http协议的呢。有没有公共的这种服务器

**Comment by imgk** [comment]
目前支持 DNS over TLS 和 DNS over HTTPS，阿里的 DoH 可以用
```json
{
    "name_server": "https://223.5.5.5:443/dns-query"
}
```

**Comment by yansong1221** [comment]
谢谢大佬指点。我还遇到个问题，我用的windivert 模式，就我正常ctrl c 结束shadow 进程第二次启动有很高的概率会崩溃

**Comment by imgk** [comment]
这个问题我不常出现，请提供具体的错误信息，不过不太影响使用，可以不用管的
