### ISSUE TITLE
protocol error: not a supported scheme: http

### ISSUE THREAD

**Issue by Filarius** [imgk/shadow#41]
I'm trying this app under Windows 10 with http(s) proxy
and have error
`protocol error: not a supported scheme: http`

this is my config
{
    "server": {
        "protocol": "http",
        "url": "http://x.x.x.x:3128"
    },
    "name_server": ["https://1.1.1.1:443/dns-query"],
    "ip_cidr_rules": {
        "proxy": [
            "198.18.0.0/16"
        ]
    },
    "geo_ip_rules": {
        "file": "Country.mmdb",
        "proxy": [],
        "bypass": [],
        "final": "proxy"
    }
}

also  i took this from your docs and it makes error trying unmarshal string into struct
` "name_server": "https://1.1.1.1:443/dns-query"`
looks like right is
` "name_server": ["https://1.1.1.1:443/dns-query"]`

**Comment by imgk** [comment]
To use http proxy, you need to build with tags "http".

`go build -v -ldflags="-s -w" -trimpath -tags="http"`

I forgot to update the docs for DNS. `"name_server": ["https://1.1.1.1:443/dns-query"]`
