### ISSUE TITLE
Since version 0.4.8, shadowsocks cannot be connected.

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#43]
Up to golang.zx2c4.com/wireguard/windows 0.4.7 it worked normally.

After that, shadowsocks will not connect.

Today's version(0.4.11) doesn't work either.

wintun tab driver is not created.

----

{
"server": {"protocol": "shadowsocks", "url": "shadowsocks://aes-256-gcm:pass@server_ip:port"},
"name_server": ["tls://8.8.8.8:853"],
"tun": {"tun_name": "tun1","tun_addr": ["10.0.0.1/30"]},
"ip_cidr_rules": {"proxy": ["0.0.0.0/1","128.0.0.0/1"]},
"app_rules": {"proxy": []},
"domain_rules": {"proxy": [],"direct": [],"blocked": []}
}

**Comment by imgk** [comment]
I have no time to fix this issue now. So, I revert `golang.zx2c4.com/wireguard/windows` back to `0.4.7' as a temporary solution.
