### ISSUE TITLE
没有编译成功吗?

### ISSUE THREAD

**Issue by fbion** [imgk/shadow#48]
user@macos ~ % go version
go version go1.16.15 darwin/amd64
user@macos ~ % go get -v -ldflags="-s -w" -trimpath -tags="socks" github.com/imgk/shadow
go/pkg/mod/github.com/imgk/shadow@v0.0.0-20220128031617-9ea50f40f661/pkg/tun/tun_darwin.go:14:2: //go:build comment without // +build comment
user@macos ~ % ls ~/go/bin
user@macos ~ % ls -l ~/go/bin
没有生成shadow?

**Comment by imgk** [comment]
go 版本低了吧

**Comment by fbion** [comment]
> go 版本低了吧

示例中的go version是1.16...
用go version go1.17.9 darwin/amd64
编译成功...
