### ISSUE TITLE
The daemon dies for no reason.

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#5]
![image](https://user-images.githubusercontent.com/46304767/79625805-8074b180-8166-11ea-916d-acad93518827.png)

**Comment by imgk** [comment]
I've also had this problem and I am working on it. Try this [pre-release version](https://1drv.ms/u/s!AgkGJqaRN6Q3hNpdDSjOAuZ3_l5emw?e=C2wZkf).

**Comment by BeOB** [comment]
The daemon is not dead yet.
The bug seems to have been fixed.
Thanks...
