### ISSUE TITLE
How do I send all UDP packets to the proxy server?

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#6]
I have a question.

How do I send all UDP packets to the proxy server?

Thanks...

**Comment by imgk** [comment]
Shadowsocks-windivert doesn’t support protocol-related rules. I want to keep this tool as simple as possible and won’t add too many features. If you really need this feature, you can build a customized version by modifying the source code to divert UDP packets only and change the program filter mode from black list to white list. Then you can divert all UDP packets except those sent by shadowsocks.

**Comment by imgk** [comment]
I found that it is not too hard to add this feature. You can try the dev branch, it provides more functions if you understand how to write a Divert filtering string.

**Comment by BeOB** [comment]
Thanks for your hard work.
