### ISSUE TITLE
There is one request to you.

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#7]
There is one request to you.

Like TCP, UDP wants to be relayed to a proxy server.

If this one thing is added, this project will be perfect.

Please...

**Comment by imgk** [comment]
I’m not sure about what’s your meaning. But this program supports sending UDP packets to a proxy server.

**Comment by BeOB** [comment]
I want the UDP packet to be like the relay function in the netstack.go

I don't know what it is, but TCP communication works fine, but not UDP(DNS queries, SNMP, etc.) communication.

**Comment by imgk** [comment]
Shadowsocks-WinDivert does not fully support the UDP protocol. To handle packets more efficiently, it treats a UDP connection more like a stream protocol. It means that it only supports a UDP connection of which the destination address would not change. I'm not sure about SNMP. DNS and QUIC are totally supported. If you send DNS messages to IPs in the proxy list with `nslookup`. You will see logs relating to diverting UDP packets. If you don't, please check your own configuration.

**Comment by BeOB** [comment]
I also confirmed that UDP relay is possible in go-tun2socks project.
(https://github.com/eycorsican/go-tun2socks)

Please refer...

**Comment by imgk** [comment]
As I said, you should check your own configuration first. I add `8.8.8.8` to the IP list, and then execute `nslookup google.com 8.8.8.8`. These are the logs showed in the cmd window.
```
2020/04/22 08:38:29 netstack.go:338: proxy 192.168.31.43:65509 <-UDP-> 8.8.8.8:53
2020/04/22 08:38:29 netstack.go:338: proxy 192.168.31.43:59210 <-UDP-> 8.8.8.8:53
2020/04/22 08:38:29 netstack.go:338: proxy 192.168.31.43:49176 <-UDP-> 8.8.8.8:53
```
![log](https://user-images.githubusercontent.com/14073640/79928419-778d2400-8475-11ea-8c3b-155ebcee78be.JPG)

**Comment by BeOB** [comment]
Thanks...
